### ISSUE TITLE
Required software

### ISSUE THREAD

**Issue by minminli521527** [lufuhao/FuhaoLab#1]
STAR, LAST, Kallisto, Salmon, R, eagle

**Comment by lufuhao** [comment]
please list the software webpage！

发自我的iPhone

在 2020年5月18日，16:23，minminli521527 <notifications@github.com> 写道：

﻿

STAR, LAST, Kallisto, Salmon, R, eagle

**Comment by huilin-al** [comment]
rstudio安装问题：
依赖: libjpeg62 但是它将不会被安装
           依赖: libssl1.0.0 但无法安装它 或
                   libssl1.0.2 但无法安装它
           依赖: libgstreamer0.10-0 但无法安装它
           依赖: libgstreamer-plugins-base0.10-0 但无法安装它

**Comment by huilin-al** [comment]
rstudio安装问题：
依赖: libjpeg62 但是它将不会被安装
           依赖: libssl1.0.0 但无法安装它 或
                   libssl1.0.2 但无法安装它
           依赖: libgstreamer0.10-0 但无法安装它
           依赖: libgstreamer-plugins-base0.10-0 但无法安装它

**Comment by huilin-al** [comment]
bamtools安装,编译安装最后一步   make DESTDIR=/build  install    ##安装(这一步看不懂）
或者conda安装搜不到镜像 @lufuhao

**Comment by minminli521527** [comment]
The softwares such as eagle,  gffread, subread, LAST, BamBam, killisto, salmon, STAR and R are required, and the relevant information is as follows:
eagle: https://github.com/tony-kuo/eagle ; https://github.com/Wendellab/homoeologGeneExpression-Coexpression/blob/master/scripts/eagle-rc.sh
gffread : https://github.com/gpertea/gffread
subread: http://subread.sourceforge.net/
LAST: http://last.cbrc.jp/
BamBam: Home Page:http://sourceforge.net/projects/bambam/
killisto: https://pachterlab.github.io/kallisto/download.html
salmon: https://combine-lab.github.io/salmon/
STAR: https://github.com/alexdobin/STAR
R: https://cloud.r-project.org/

**Comment by lufuhao** [comment]
> 
> 
> bamtools安装,编译安装最后一步 make DESTDIR=/build install ##安装(这一步看不懂）
> 或者conda安装搜不到镜像 @lufuhao

Solved

**Comment by lufuhao** [comment]
> 
> 
> rstudio安装问题：
> 依赖: libjpeg62 但是它将不会被安装
> 依赖: libssl1.0.0 但无法安装它 或
> libssl1.0.2 但无法安装它
> 依赖: libgstreamer0.10-0 但无法安装它
> 依赖: libgstreamer-plugins-base0.10-0 但无法安装它

sudo apt install libssl-dev libjpeg62-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

**Comment by lufuhao** [comment]
scripts for eagle gffread subread last bambam are ready.

check out the requirements in README

发自我的iPhone

在 2020年5月19日，21:48，minminli521527 <notifications@github.com> 写道：

﻿

The softwares such as eagle, gffread, subread, LAST, BamBam, killisto, salmon, STAR and R are required, and the relevant information is as follows:
eagle: https://github.com/tony-kuo/eagle ; https://github.com/Wendellab/homoeologGeneExpression-Coexpression/blob/master/scripts/eagle-rc.sh
gffread : https://github.com/gpertea/gffread
subread: http://subread.sourceforge.net/
LAST: http://last.cbrc.jp/
BamBam: Home Page:http://sourceforge.net/projects/bambam/
killisto: https://pachterlab.github.io/kallisto/download.html
salmon: https://combine-lab.github.io/salmon/
STAR: https://github.com/alexdobin/STAR
R: https://cloud.r-project.org/

**Comment by lufuhao** [comment]
install R in ubuntu 20

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9

sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'

sudo apt update

sudo apt install r-base
