### ISSUE TITLE
install biosoft error 

### ISSUE THREAD

**Issue by huilin-al** [lufuhao/FuhaoLab#5]
1.sbatch inst_abyss-latestGitHub.sh
configure error:configure: error: ABySS should be compiled with Google sparsehash to
Error: cmd failed
CMD: ./configure --prefix=/home/hpcsoft/TestSoft/abyss/v2.2.5-d908f485/x86_64 --enable-maxk=256
可能要加上这个--without-sparsehash
2.sbatch inst_GetOrganelle-latestGitHub.sh
Error: cmd failed
CMD: pip3 install --user sympy
我之前是conda安装

**Comment by lufuhao** [comment]
solved
