### ISSUE TITLE
Lack of software

### ISSUE THREAD

**Issue by huilin-al** [lufuhao/FuhaoLab#6]
1.Edena——http://www.genomic.ch/edena.php
2.SOAPdenovo2(conda install)——conda install -c conda-forge -c defaults -c r -c bioconda soapdenovo2
3.fastq-tools——https://homes.cs.washington.edu/~dcjones/fastq-tools/
Add a message if it is missing later

**Comment by lufuhao** [comment]
Edena and fastq-tools are ready.
Ignore SOAPdenovo
