### ISSUE TITLE
install biosoft error

### ISSUE THREAD

**Issue by huilin-al** [lufuhao/FuhaoLab#7]
1.sbatch inst_nextDenovo-v2.3.0.sh
ModuleNotFoundError: No module named 'psutil'
Error: cmd failed
./nextDenovo test_data/run.cfg
Please update to the latest version: v2.3.1, current version: v2.3.0
2.sbatch inst_sga-latestGitHub.sh
The bamtools library must be installed (http://github.com/pezmaster31/bamtools). You can specify its path with the --with-bamtools=PATH option
Error: cmd failed
3.sbatch inst_ray-latestGitHub.sh
/var/lib/slurm-llnl/slurmd/job00716/slurm_script: 第 30 行： cd: /home/hpcsoft/TestSoft/ray/ray: 没有那个文件或目录
mkdir -p /home/hpcsoft/TestSoft/ray/-/x86_64
make MPI_IO=y PREFIX=/home/hpcsoft/TestSoft/ray/-/x86_64 MAXKMERLENGTH=251 HAVE_LIBZ=y HAVE_LIBBZ2=y ASSERT=n FORCE_PACKING=y

**Comment by lufuhao** [comment]
1. update to inst_nextDenovo-v2.3.1.sh
2. need `module load bamtools` first
3. corrected
