### ISSUE TITLE
biosoft questions

### ISSUE THREAD

**Issue by huilin-al** [lufuhao/FuhaoLab#8]
1.inst_NOVOPlasty-latestGitHub.sh
Error: failed to install NOVOPlasty-v4.2-2379162
2.inst_phymer-latestGitHub.sh
ModuleNotFoundError: No module named 'Bio'
Error: failed to install phy-mer-v1.0-8373d72
3.inst_unicycler-latestGitHub.sh
Unicycler is an assembly pipeline for bacterial genomes.
Unicycle has been loaded with environmental variables and still can’t be found, and unicycle is a bacterial gene assembly tool, can it be used in plants?

**Comment by lufuhao** [comment]
1. Updated

2. install biopython first
pip3 install --user biopython
inst_phymer-latestGitHub.sh

3. inst_unicycler-latestGitHub.sh
Solved
